name: TODO Checker Javascript Action
description: Checks for TODO Comments in your codebase
inputs:
  src-path:
    description: Path to the files to Check
    required: true
    default: ./src
runs:
  using: 'node16'
  main: 'dist/index.js'