name: Intro - Custom Workflow

run-name: ${{github.actor}}'s custom workflow run

on:
    workflow_dispatch:

jobs:
    execute:
        runs-on: ubuntu-latest

        steps:
            - run: echo This job was automatically triggered by ${{github.event_name}} event
            - run: echo This job is now running on a ${{runner.os}} server hosted by github
            - run: echo The name of this branch is ${{github.ref}} and the repo name is ${{github.repository}}

            - name: Check code
              uses: actions/checkout@v4

            - name: List files in directory
              run: |
                ls ${{github.workspace}}

            - run: echo This jobs status is ${{job.status}}

            - name: Adding markdown
              run: echo "### Hello World! :rocket:" >> "$GITHUB_STEP_SUMMARY"

            - name: Hello World
              uses: actions/hello-world-javascript-action@main
              with:
                who-to-greet: 'Haaland'
              id: hello_world

            - name: Echo Greeting's time
              run: echo The time was ${{steps.hello_world.outputs.time}}
